# Site settings
title: "Group Work"
description:  make a blog

# Files
baseurl:
pagesdir: pages

email:  tian.1.lan@kcl.ac.uk
url: ""
search: true
share: true
comments: true

# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime: true

# Specify the average Words per minute. If not defined, 180 will be used
wpm: 200



# Social networking links used in footer. Update and remove as you like.
twitter_username: Jekyll


 
# Internal nav
nav:
 content list: "root_url/writing/"
 occasion: "root_url/gallery/"
 about: "root_url/about/"


# Server
destination:      	 ./_site
port:             	 4000


#dependencies
# Gems
gems:
  - jekyll-paginate


# Build settings
highlighter:         rouge
markdown:           kramdown
kramdown:
    extensions:     
     - Hard_wrap
     - no_intra_emphasis
     - strikethrough
     - fenced_code_blocks
     - autolink
     - tables
     - with_toc_data
     - highlight
     - footnotes
    input:          GFM
sass:
    style:          :compressed
paginate: 5
paginate_path: "/writing/page:num/"
permalink: "/writing/:title/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
slugify: "pretty"


         
